webdoc-labs/webdoc

packages/webdoc-cli/src/config.js

Using the Lodash merge to for merging two objects.

Merge the userconfig with defaultconfig

---

azure-example-documentation.yml

Trying to disable the PR: trigger

Removed the PR trigger on example docs generation

---

example/example.api.json
example/src/Vector.js
packages/webdoc-default-template/helper/crawl/crawl-reference-explorer.js
packages/webdoc-default-template/publish.js

* enums in explorer
* typedefs, enumerations, and functions get their own standalone HTML 
page
* no more -_.html files

Fixes to template output

---

package.json
watchdog.ps1

Add PowerShell powered watchdog.
This should work cross-platform, as I use pwsh.
- Tested on Windows.
Usage:
```
yarn watchdog
```

chore: add watchdog

---

packages/webdoc-model/src/index.js
packages/webdoc-model/src/query/index.js
packages/webdoc-model/src/query/parse.js
packages/webdoc-model/src/query/query.js
packages/webdoc-model/src/query/step.js
packages/webdoc-model/src/query/types.js
packages/webdoc-model/src/query/variant.js
packages/webdoc-model/test/query/parse.js
packages/webdoc-template-library/src/pipeline-elements/TemplateTagsResolver.js

https://docs.google.com/document/d/e/2PACX-1vRlI-wcBHt9TEJ7xqSvqBvJd4nX9MItFxsKC_goGUT39aBJvj8nJ1BWwqsDpV3z9WG2xNwMF8PoQ072/pub

[Feature]: Document Path Language query support in @webdoc/model

---

packages/webdoc-model/src/doc.js

Assign new ID in cloneDoc

---

packages/webdoc-cli/src/index.js
packages/webdoc-default-template/helper/crawl/crawl.js
packages/webdoc-default-template/publish.js
packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js

Adds the packageName to urls in tree mode

Add packageName prefix in all URLs

---

packages/webdoc-parser/src/transformer/symbol-to-doc.js
packages/webdoc-parser/test/lang-ts.js
packages/webdoc-parser/test/parse-ts.js

Fix: Inference for types and default values in fields

---

packages/webdoc-parser/src/symbols-babel/build-symbol-tree.js
packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/src/tag-parsers/index.js
packages/webdoc-parser/src/tag-parsers/parseSimple.js
packages/webdoc-parser/src/transformer/symbol-to-doc.js
packages/webdoc-parser/src/types/Symbol.js
packages/webdoc-parser/test/lang-js.js
packages/webdoc-parser/test/lang-ts.js
packages/webdoc-parser/test/parse-ts.js
packages/webdoc-types/index.js.flow

Feature: First-class readonly support

---

packages/webdoc-parser/src/symbols-babel/build-symbol-tree.js
packages/webdoc-parser/test/lang-js.js

Fix crash on rest element applied to object destructuring

---

common/config/rush/pnpm-lock.yaml
packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/test/lang-js.js
packages/webdoc-parser/test/lang-ts.js

Feature: Add type interference for strings, numbers, and booleans.

---

packages/webdoc-cli/src/config.js
packages/webdoc-parser/src/transformer/mod-sort-members.js

Fixes #88. This is a backward compatible change.

Make sorting parameters arrays in configuration

---

packages/webdoc-parser/test/parse-tag-variations.js
packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js

Fixes #103 
Add extra guard against null options in LinkerPluginImpl.linkTo; add unit-test for no-type @returns tag.
Adds unit-tests that fails to reproduce #104

Fix @stepanacar's bug

---

packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/test/parse-ts.js

Fix - Private access modifier not inferred from TypeScript

---

packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/test/lang-ts.js

Fix Interface properties not getting inference

---

example/src/Car.ts
packages/webdoc-parser/.flowconfig
packages/webdoc-parser/src/symbols-babel/build-symbol-tree.js
packages/webdoc-parser/src/symbols-babel/extract-metadata.js
packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/src/transformer/mod-prune.js
packages/webdoc-parser/src/transformer/symbol-to-doc.js
packages/webdoc-parser/src/types/Symbol.js
packages/webdoc-parser/test/parse-ts.js
packages/webdoc-types/index.js.flow

Add support for TypeScript parameter properties

---

packages/webdoc-default-template/static/scripts/default-template.js
packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/src/types/Symbol.js
packages/webdoc-parser/test/parse-ts.js

Fix inference for getter/setter property data types

---

packages/webdoc-model/src/data-type.js
packages/webdoc-parser/src/symbols-babel/extract-metadata.js
packages/webdoc-parser/test/lang-flow.js
packages/webdoc-parser/test/lang-ts.js

Add support for parsing type parameters in data types

---

packages/webdoc-parser/test/lang-ts.js

Chore: Add symbol level unit test for data type inference

---

.idea/webdoc.iml
common/config/rush/command-line.json
packages/webdoc-default-template/static/styles/algolia.css

Chore: Better search styling for Algolia integration

---

common/changes/@webdoc/parser/fix-inferred-param-types_2022-02-19-18-05.json
common/changes/@webdoc/parser/fix-inferred-param-types_2022-02-19-18-06.json
packages/webdoc-parser/src/symbols-babel/extract-metadata.js
packages/webdoc-parser/src/symbols-babel/extract-symbol.js
packages/webdoc-parser/test/lang-ts.js

Fix: Primitive type inferred based on parameter default value

---

common/changes/@webdoc/model/fix-inherited-overloads_2022-02-19-21-21.json
common/changes/@webdoc/parser/fix-inherited-overloads_2022-02-19-21-21.json
packages/webdoc-model/index.js.flow
packages/webdoc-model/src/doc.js
packages/webdoc-model/src/query/parse.js
packages/webdoc-model/src/query/query.js
packages/webdoc-model/src/query/types.js
packages/webdoc-model/src/query/variant.js
packages/webdoc-model/test/query/query.js
packages/webdoc-parser/src/transformer/mod-discover-members.js
packages/webdoc-parser/src/transformer/mod-es5-constructor.js
packages/webdoc-parser/test/parse-ts.js

Fix: Make all method overloads get properly inherited into child classes

---

.idea/webdoc.iml
packages/webdoc-parser/src/symbols-babel/extract-metadata.js
packages/webdoc-parser/test/lang-ts.js
packages/webdoc-parser/test/parse-ts.js

Fix: Don't pass undefined identifier for array pattern varargs

---

.idea/webdoc.iml
packages/webdoc-default-template/static/scripts/default-template.js
packages/webdoc-parser/src/transformer/mod-es5-constructor.js
packages/webdoc-parser/test/parse.js

https://github.com/melonjs/melonJS

Feature: Support @classdesc for ES6 classes

---

packages/webdoc-parser/src/assembler/mod-resolve-assigned-members.js
packages/webdoc-parser/src/symbols-babel/build-symbol-tree.js
packages/webdoc-parser/src/symbols-babel/extract-metadata.js
packages/webdoc-parser/src/transformer/transform.js
packages/webdoc-parser/src/types/Symbol.js

https://github.com/melonjs/melonJS/issues/1089

Feature: Better debug output with symbol source location in various places

---

packages/webdoc-parser/src/symbols-babel/extract-metadata.js
packages/webdoc-parser/test/lang-flow.js
packages/webdoc-parser/test/lang-ts.js

Found in melonJS: https://github.com/melonjs/melonJS/issues/1089

Feature: Object pattern parameter parsing

---

packages/webdoc-cli/src/config.js
packages/webdoc-default-template/helper/renderer-plugins/preprocess.js
packages/webdoc-default-template/publish.js
packages/webdoc-default-template/tmpl/components/content/text.tmpl
packages/webdoc-default-template/tmpl/components/member/index.tmpl
packages/webdoc-default-template/tmpl/components/member/params.tmpl
packages/webdoc-default-template/tmpl/components/member/returns.tmpl
packages/webdoc-default-template/tmpl/document.tmpl

https://github.com/melonjs/melonJS/issues/1089

Feature: Add support for copying assets and replace img src with the proper path in @webdoc/default-template

---

language/language-parser/rollup.config.mjs
language/language-parser/src/transformer/merge-returns.js
language/language-parser/src/transformer/symbol-to-doc.js
language/language-parser/test/parse-ts.js

Ensure params, returns, typeParameters, extends, implements are not undefined

---

language/language-parser/src/transformer/symbol-to-doc.js
language/language-parser/test/parse-ts.js

Add test for literal property type

---

core/webdoc-default-template/src/app/components/Explorer/helpers.js

Add matching for URLs without index.html in explorer

---

core/webdoc-default-template/src/protocol/index.js
core/webdoc-default-template/src/styles/header.scss

1. Fix CSS causing setting button to be offscreen on Safari
2. Fix "this page has been updated" message on 2nd page loads

Fixes related to service worker

---

example/src/ExampleFactory.js
language/language-parser/src/tag-parsers/parseSimple.js
language/language-parser/test/tag-parsers/parseExample.js

Trim snippets in @example code
