- CONTRIBUTING.md
Updating the Contribution page as the rush package is not `rush` but is `@microsoft/rush`.
> The Rush Package has changed names

- packages/webdoc-parser/src/symbols-babel/extract-metadata.js
This will prevent warnings from popping up in a typescript codebase with `unknown` types.
> [Fix]: TS Unknown keyword

- .gitignore
- common/config/rush/pnpm-lock.yaml
- example.api.json
- example/package.json
- packages/webdoc-cli/package.json
- packages/webdoc-cli/src/config.js
- packages/webdoc-cli/src/index.js
- packages/webdoc-cli/src/sources/index.js
- packages/webdoc-cli/src/sources/packages.js
- packages/webdoc-default-template/helper/crawl/crawl-reference-explorer.js
- packages/webdoc-legacy-template/.eslintrc.json
- packages/webdoc-legacy-template/babel.config.json
- packages/webdoc-legacy-template/package.json
- packages/webdoc-parser/src/parse.js
- packages/webdoc-parser/src/symbols-babel/build-symbol-tree.js
- packages/webdoc-parser/src/symbols-babel/index.js
- packages/webdoc-parser/src/tag-parsers/parseProperty.js
- packages/webdoc-parser/src/transformer/document-tree-modifiers.js
- packages/webdoc-parser/src/transformer/mod-package-api.js
- packages/webdoc-parser/src/types/LanguageIntegration.js
- packages/webdoc-parser/src/types/Symbol.js
- packages/webdoc-parser/test/parse.js
- packages/webdoc-types/index.js.flow
- scripts/configureWebdocTesting.js
- webdoc.conf.json
This PR would introduce multi-package support in webdoc. It adds the `SourceFile` API to the documentation model.
webdoc now stores information about each source file in the codebase. Each source file points to a `PackageDoc`.
Each `PackageDoc` has an `api` field that stores the top-level exported members. These are inferred in the doc-tree-modifier packageApi.
The default template uses a special traversal loop to stay within each package in multi-package mode to generate the api explorer.
> Multi-package support in @webdoc/cli, @webdoc/parser, @webdoc/default-template!

- packages/webdoc-template-library/src/pipeline-elements/TemplateTagsResolver.js
- packages/webdoc-template-library/test/pipeline-elements/TemplateTagsResolver.js
This PR adds support for alternative link formats. Example of where this is [used in PixiJS](http://pixijs.download/dev/docs/PIXI.BitmapFont.html#from).
Reference: https://jsdoc.app/tags-inline-link.html
* `{@link namepathOrURL}` ✅ 
* `[link text]{@link namepathOrURL}` ✅ 
* `{@link namepathOrURL|link text}` ❌    **Added Support**
* `{@link namepathOrURL link text (after the first space)}` ❌    **Added Support**
> Support Alternative Link Formats

- common/config/rush/pnpm-lock.yaml
- packages/webdoc-cli/package.json
- packages/webdoc-cli/src/shims.js
- packages/webdoc-cli/src/sources/packages.js
- packages/webdoc-default-template/helper/crawl/crawl-reference-explorer.js
- packages/webdoc-default-template/helper/crawl/crawl.js
- packages/webdoc-default-template/helper/explorer.js
- packages/webdoc-default-template/helper/linker.js
- packages/webdoc-default-template/helper/renderer-plugins/signature.js
- packages/webdoc-default-template/publish.js
- packages/webdoc-model/package.json
- packages/webdoc-model/src/doc.js
- packages/webdoc-model/src/query/query.js
- packages/webdoc-model/src/query/step.js
- packages/webdoc-model/src/query/variant.js
- packages/webdoc-template-library/package.json
- packages/webdoc-template-library/src/SymbolLinks.js
- packages/webdoc-template-library/src/TemplateRenderer.js
- packages/webdoc-template-library/src/index.js
- packages/webdoc-template-library/src/pipeline-elements/TemplateTagsResolver.js
- packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js
- packages/webdoc-template-library/src/template-plugins/MixinPlugin.js
- packages/webdoc-template-library/src/template-plugins/Plugin.js
- packages/webdoc-template-library/src/template-plugins/RuntimePlugin.js
- packages/webdoc-template-library/src/template-plugins/index.js
- packages/webdoc-template-library/test/pipeline-elements/TemplateTagsResolver.js
Fixes #42
I DID IT! The `LinkerPlugin` API replaces the (deprecated) `SymbolLinks` API. It uses a mapping between the document IDs (rather than canonical paths) to the URI information. Then, a `queryCache` is used to cache DPL queries to links.
> [Feature]: Upgraded linker API

- packages/webdoc-parser/src/tag-parsers/parseProperty.js
- packages/webdoc-parser/test/tag-parsers/parseProperty.js
Fixes #43.
Use a different regex that matches non-whitespace characters instead of only word characters.
> Better regex for @property value parsing to capture non-word, non-whitespace characters

- packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js
I wonder why this didn't affect the default template 🤔. Found when testing pixi-webdoc-template with the linker plugin.
> [Fix]: Query cache should link around cached URI

- packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js
> Replace "<", ">" tokens in data type links with HTML safe counterparts.

- packages/webdoc-default-template/helper/renderer-plugins/signature.js
- packages/webdoc-template-library/src/pipeline-elements/TemplateTagsResolver.js
- packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js
- packages/webdoc-template-library/test/pipeline-elements/TemplateTagsResolver.js
Also, pass `{htmlSafe:false}` in default template signatures b/c they are inside &lt;pre /&gt; tags.
> [Feature]: Resolve {@code } tags

- azure-pipelines.yml
- example.api.json
- packages/webdoc-parser/src/symbols-babel/extract-metadata.js
- packages/webdoc-parser/src/symbols-babel/index.js
This PR adds support for resolving AST nodes into flow data types. Running `build-next` in @webdoc/example will generate correct signatures from the webdoc codebase.
> Add support for flow types

- packages/webdoc-parser/src/symbols-babel/build-symbol-tree.js
- packages/webdoc-parser/src/symbols-babel/index.js
- packages/webdoc-parser/test/lang-js.js
- packages/webdoc-parser/test/lang-ts.js
> Ship support for decorators in source code at parsing level

- example/webdoc.conf.json
- packages/webdoc-cli/src/config.js
- packages/webdoc-cli/src/index.js
- packages/webdoc-cli/src/sources/index.js
Partially addresses #84 
Behavior defined here: https://jsdoc.app/about-configuring-jsdoc.html
> Match JSDoc in terms of config include/exclude/includePattern/excludePattern

- azure-pipelines.yml
- packages/webdoc-default-template/helper/renderer-plugins/signature.js
- packages/webdoc-parser/src/symbols-babel/extract-symbol.js
- packages/webdoc-parser/test/lang-ts.js
Fixes #79 
Edited the CI so failures prevent the PR from getting merged. This is b/c we don't have any linting or type checking errors on master.
> Resolve default value expressions for negative numbers, fail in CI on linting & unit-testing

- packages/webdoc-template-library/src/template-plugins/LinkerPlugin.js
For linking against another API, this change provides a way to do that even if the API being included doesn't contain a `siteDomain` in the metadata. In general, this makes linking much more flexible and portable as well as making it easier to test locally.
Use-case for this change is https://github.com/pixijs/guides which needs to link against https://pixijs.download/release/docs/pixi.api.json, but that JSON doesn't define `siteDomain` in the webdoc config.
> Provide siteDomain and siteRoot fallback

- packages/webdoc-default-template/tmpl/components/members-explorer/index.tmpl
- packages/webdoc-default-template/tmpl/document.tmpl
Fixes #161
And also hide summary / right sidebar if no children to show
> Fix: Make standalone function pages show parameters, returns tables

- packages/webdoc-parser/src/tag-parsers/parseSimple.js
- packages/webdoc-parser/src/transformer/symbol-to-doc.js
- packages/webdoc-parser/test/parse.js
Fixes #163
**This PR Addresses:**  
[JavaScript method overloads not being parsed](https://github.com/webdoc-labs/webdoc/issues/163)  
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
> JavaScript method overloads not being parsed

- core/webdoc-template-library/src/template-plugins/LinkerPlugin.js
Fixes #181
This work prevents LinkerPlugin from generating multiple case-sensitive versions of the same file, e.g. timer and Timer. It also prevents a potential issue of getFileRecord returning a brand new record each time.
> Fix case-sensitive filename collision in LinkerPlugin

- core/webdoc-default-template/helper/renderer-plugins/signature.js
> Fix: Don't append to class signature if extends, implements arrays are empty

- core/webdoc-default-template/tmpl/layout.tmpl
- core/webdoc-legacy-template/tmpl/layout.tmpl
The URL scheme is missing for `googlecode.min.css`:
```html
<link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/googlecode.min.css">
```
It works fine on a real website, but if you open the output `.html` file locally, the browser will assume the scheme is `file:`, causing the error:
Adding an explicit `https:` solves the problem.
> Add missing URL scheme

- core/webdoc-cli/src/config.js
Recently I found that the version number of Webdoc shown in the generated pages is wrong. For example, at the bottom of <https://pixijs.download/v7.1.2/docs/index.html>:
> Documentation generated by Webdoc 1
I dig deeper and found the `version.number` is still `1` in `defaultConfig`. This PR fixes this problem.
> Update version.number in defaultConfig
